backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $this->layout = 'blank';

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\Order;
use common\models\Tickets;
use frontend\components\Helpers;
use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\base\Security;
use yii\data\ActiveDataProvider;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Tickets::find(),
            'pagination' => [
                'pageSize' => 15,
            ],
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider
        ]);
    }
    /**
     * Order.
     *
     * @return mixed
     */
    public function actionOrder(int $id)
    {
        $model = Tickets::findOne($id);
        if (!$model){
            throw new \yii\web\NotFoundHttpException('The requested page does not exist.');
        }
        $order = new Order();
        $order->user_name = Yii::$app->security->generateRandomString(6);
        $order->ticket_id = $model->id;
        $order->save();

        Yii::$app->session->setFlash('success', "Thank you. Your order in process");

        return $this->redirect(['site/index']);
    }
}

frontend/views/site/_ticket.php
<?php

/* @var $this yii\web\View */
/* @var $model \common\models\Tickets */

use yii\helpers\Html;

?>

<div class="col-lg-offset-0 col-lg-4 col-md-offset-0 col-md-4 col-sm-offset-0 col-sm-6 col-xs-6 col-lg-offset-1 col-exs-10 ticket-item">
    <div class="ticket-image-wrapper">
        <div class="ticket-name">
            <?= Html::encode($model->title) ?>
        </div>
        <img src="<?=$model->getImage()?>" alt="<?= Html::encode($model->title) ?>" class="ticket-image">
    </div>
    <div class="ticket-info">
        <div class="pull-left price-wrapper">
            <span class="dollar-icon">$</span>
            <span class="price"><?=$model->price?></span>
        </div>
        <div class="clearfix"></div>
        <br>
        <div class="description">
            <?=$model->description?>
        </div>
        <div class="bottom-info">
            <div class="button-wrapper button-order">
                <a href="<?=\yii\helpers\Url::to(['site/order', 'id' => $model->id])?>" class="buy-button">Купить</a>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\widgets\ListView;

$this->title = 'My Yii Application';
?>
<div class="tickets-header">
    <p style="text-align:center"><span style="font-size:24px"><strong>Получи лучшие курсы от самых именитых тренеров!</strong></span></p>
</div>
<div class="tickets-wrapper">
    <div class="tickets-list">
        <div class="row">
            <?= ListView::widget([
                'dataProvider' => $dataProvider,
                'itemView' => '_ticket',
                'summary'=>''
            ]);?>
        </div>
    </div>
</div>